import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/models.dart';
import 'food_service.dart';

class ReportService {
  final FoodService _foodService;

  ReportService(this._foodService);

  Future<Uint8List> generateReport(
    DateTime start,
    DateTime end,
    Profile? profile, {
    required List<FoodLog> foodLogs,
    required List<WeightLog> weightLogs,
    required List<ExerciseLog> exerciseLogs,
  }) async {
    final summaries = await _foodService.getDailySummariesRange(start, end);
    final pdf = pw.Document();

    final dateFormat = DateFormat('MMM d, yyyy');
    final startStr = dateFormat.format(start);
    final endStr = dateFormat.format(end);

    final isDaily = start.year == end.year && start.month == end.month && start.day == end.day;
    final title = isDaily ? 'Daily Nutrition Report' : 'Monthly Progress Report';

    // === Calculations ===
    
    // 1. Nutrition Averages
    double avgCal = 0, avgPro = 0, avgCarb = 0, avgFat = 0;
    if (summaries.isNotEmpty) {
      avgCal = summaries.map((e) => e.totalCalories).reduce((a, b) => a + b) / summaries.length;
      avgPro = summaries.map((e) => e.totalProteinG).reduce((a, b) => a + b) / summaries.length;
      avgCarb = summaries.map((e) => e.totalCarbsG).reduce((a, b) => a + b) / summaries.length;
      avgFat = summaries.map((e) => e.totalFatG).reduce((a, b) => a + b) / summaries.length;
    }

    // 2. Exercise Stats ("Kitna Exercise Kiya")
    int totalExerciseMin = 0;
    int totalExerciseCal = 0;
    for (final log in exerciseLogs) {
      totalExerciseMin += log.durationMinutes;
      totalExerciseCal += log.caloriesBurned;
    }

    // 3. Impact Analysis ("Fayda/Ghata")
    double weightChange = 0;
    if (weightLogs.length >= 2) {
      weightChange = weightLogs.last.weightKg - weightLogs.first.weightKg;
    }

    // 4. "Kya Khaya" (Top Foods)
    final foodFrequency = <String, int>{};
    for (final log in foodLogs) {
      foodFrequency[log.foodName] = (foodFrequency[log.foodName] ?? 0) + 1;
    }
    final sortedFoods = foodFrequency.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final topFoods = sortedFoods.take(5).toList();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(title, startStr, endStr, profile),
            pw.SizedBox(height: 20),
            
            // Section 1: Nutrition Summary ("Kitna Khaya")
            _buildSectionTitle('Nutrition Summary (Average)'),
            _buildSummaryTable(avgCal, avgPro, avgCarb, avgFat, profile),
            pw.SizedBox(height: 20),

            // Section 2: Exercise Analysis ("Kitna Exercise Kiya")
            _buildSectionTitle('Exercise & Activity'),
            _buildExerciseAnalysis(totalExerciseMin, totalExerciseCal, exerciseLogs),
             pw.SizedBox(height: 20),

            // Section 3: Impact Analysis ("Fayda / Ghata")
            _buildSectionTitle('Impact Analysis (Fayda/Ghata)'),
            _buildImpactAnalysis(weightChange, totalExerciseCal, weightLogs, profile),
            pw.SizedBox(height: 20),

            // Section 4: Diet Analysis ("Kya Khaya")
            _buildSectionTitle('Top Foods Consumed'),
             _buildTopFoodsList(topFoods),
            pw.SizedBox(height: 20),

            if (!isDaily) _buildDailyBreakdown(summaries),
            if (isDaily || exerciseLogs.isNotEmpty) ...[
               pw.SizedBox(height: 10),
               pw.Text('Detailed logs attached below...', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10)),
            ],
            
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Text('Generated by CoCal App', style: const pw.TextStyle(color: PdfColors.grey500, fontSize: 10)),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildSectionTitle(String text) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Text(text, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
    );
  }

  pw.Widget _buildHeader(String title, String start, String end, Profile? profile) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('CoCal', style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
            pw.Text(title, style: const pw.TextStyle(fontSize: 18)),
            pw.SizedBox(height: 4),
            pw.Text('Period: $start - $end', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          ],
        ),
        if (profile != null)
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(profile.fullName ?? 'User', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text('Target: ${profile.goal}', style: const pw.TextStyle(fontSize: 10)),
              pw.Text('Start Wt: ${profile.currentWeightKg ?? "-"} kg', style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
      ],
    );
  }

  pw.Widget _buildExerciseAnalysis(int duration, int calories, List<ExerciseLog> logs) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildStatItem('Total Time', '${(duration / 60).toStringAsFixed(1)} hrs'),
              _buildStatItem('Calories Burned', '$calories kcal'),
              _buildStatItem('Workouts', '${logs.length}'),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildStatItem(String label, String value) {
    return pw.Column(
      children: [
         pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
         pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
      ],
    );
  }

  pw.Widget _buildImpactAnalysis(double weightChange, int exerciseCal, List<WeightLog> weights, Profile? profile) {
    String verdict = "Stable";
    if (weightChange < -0.5) verdict = "Weight Loss (Fayda)";
    if (weightChange > 0.5) verdict = "Weight Gain (Possible Muscle/Fat)";
    if (profile?.goal == 'lose' && weightChange < 0) verdict = "Success: Losing Weight";
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.teal, width: 1),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Net Result:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(verdict, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: weightChange < 0 ? PdfColors.green700 : PdfColors.orange700)),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Text('Stats:', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
          pw.Text('• Weight Change: ${weightChange > 0 ? "+" : ""}${weightChange.toStringAsFixed(1)} kg'),
          pw.Text('• Total Activity Burn: $exerciseCal kcal'),
        ],
      ),
    );
  }

  pw.Widget _buildTopFoodsList(List<MapEntry<String, int>> foods) {
    if (foods.isEmpty) return pw.Text('No food data available.');
    
    return pw.TableHelper.fromTextArray(
      context: null,
      headers: ['Food Item', 'Frequency'],
      data: foods.map((e) => [e.key, '${e.value} times']).toList(),
      columnWidths: {0: const pw.FlexColumnWidth(2), 1: const pw.FlexColumnWidth(1)},
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
    );
  }

  pw.Widget _buildSummaryTable(double cal, double pro, double carb, double fat, Profile? profile) {
    return pw.TableHelper.fromTextArray(
      context: null,
      headers: ['Metric', 'Average', 'Target', 'Status'],
      data: [
        ['Calories', '${cal.round()} kcal', '${profile?.dailyCalorieTarget ?? 2000}', _getStatus(cal, profile?.dailyCalorieTarget ?? 2000)],
        ['Protein', '${pro.round()}g', '${profile?.proteinTargetG ?? 60}', _getStatus(pro, profile?.proteinTargetG ?? 60)],
        ['Carbs', '${carb.round()}g', '${profile?.carbsTargetG ?? 250}', _getStatus(carb, profile?.carbsTargetG ?? 250)],
        ['Fat', '${fat.round()}g', '${profile?.fatTargetG ?? 65}', _getStatus(fat, profile?.fatTargetG ?? 65)],
      ],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
    );
  }

  String _getStatus(double current, num target) {
    final diff = (current - target).abs();
    final percentage = (diff / target) * 100;
    if (percentage <= 10) return 'On Track';
    if (current > target) return 'High';
    return 'Low';
  }

  pw.Widget _buildDailyBreakdown(List<DailySummary> summaries) {
    if (summaries.isEmpty) return pw.Text('No daily data.');

    final dateFormat = DateFormat('EEE, MMM d');
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _buildSectionTitle('Daily Breakdown'),
        pw.TableHelper.fromTextArray(
          headers: ['Date', 'Cals', 'Pro', 'Carb', 'Fat'],
          data: summaries.take(14).map((s) => [ // Limit to 2 weeks for cleaner page
            dateFormat.format(s.logDate),
            s.totalCalories,
            s.totalProteinG.round(),
            s.totalCarbsG.round(),
            s.totalFatG.round(),
          ]).toList(),
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
          cellStyle: const pw.TextStyle(fontSize: 10),
        ),
      ],
    );
  }

  pw.Widget _buildDetailedFoodLogs(List<FoodLog> logs) {
      if (logs.isEmpty) return pw.SizedBox();
      return _buildTopFoodsList([]);
  }

  Future<Uint8List> generateYearlyCertificate({
    required int year,
    required Profile? profile,
    required List<DailySummary> summaries,
    required List<WeightLog> weightLogs,
    required List<ExerciseLog> exerciseLogs,
  }) async {
    final pdf = pw.Document();

    final monthlyStats = <int, _MonthStat>{};
    for (int i = 1; i <= 12; i++) {
   monthlyStats[i] = _MonthStat(month: i);
    }

    for (final s in summaries) {
   if (s.logDate.year == year) {
     monthlyStats[s.logDate.month]?.addSummary(s, profile);
   }
    }

    for (final w in weightLogs) {
   if (w.loggedAt.year == year) {
     monthlyStats[w.loggedAt.month]?.addWeight(w);
   }
    }

    for (final e in exerciseLogs) {
   if (e.loggedAt.year == year) {
     monthlyStats[e.loggedAt.month]?.addExercise(e);
   }
    }

    double totalScore = 0;
    int monthsWithData = 0;
    _MonthStat? bestMonth;

    for (final stat in monthlyStats.values) {
   stat.calculateScore();
   if (stat.hasData) {
     totalScore += stat.score;
     monthsWithData++;
     if (bestMonth == null || stat.score > bestMonth.score) {
    bestMonth = stat;
     }
   }
    }

    final averageScore = monthsWithData > 0 ? totalScore / monthsWithData : 0.0;
    final badge = _getBadge(averageScore);

    pdf.addPage(
   pw.Page(
     pageFormat: PdfPageFormat.a4,
     margin: const pw.EdgeInsets.all(32),
     build: (pw.Context context) {
    return pw.Stack(
      children: [
        pw.Container(
       decoration: pw.BoxDecoration(
         border: pw.Border.all(color: PdfColors.amber, width: 5),
         borderRadius: pw.BorderRadius.circular(16),
       ),
        ),
        pw.Padding(
       padding: const pw.EdgeInsets.all(32),
       child: pw.Column(
         crossAxisAlignment: pw.CrossAxisAlignment.center,
         children: [
        pw.Text('CERTIFICATE OF ACHIEVEMENT', 
          style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.amber800)),
        pw.SizedBox(height: 20),
        pw.Text('This certifies that', style: const pw.TextStyle(fontSize: 16)),
        pw.SizedBox(height: 10),
        pw.Text(profile?.fullName?.toUpperCase() ?? 'COCAL USER', 
          style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold, decoration: pw.TextDecoration.underline)),
        pw.SizedBox(height: 20),
        pw.Text('Has successfully tracked their health journey for the year', style: const pw.TextStyle(fontSize: 14)),
        pw.SizedBox(height: 10),
        pw.Text('$year', style: pw.TextStyle(fontSize: 48, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
        pw.SizedBox(height: 30),
        pw.Divider(),
        pw.SizedBox(height: 30),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
          children: [
            _buildCertStat('Yearly Score', '${averageScore.toStringAsFixed(1)}/10'),
            _buildCertStat('Achievement', badge),
            _buildCertStat('Best Month', bestMonth != null ? DateFormat('MMMM').format(DateTime(year, bestMonth.month)) : '-'),
          ],
        ),
        pw.Spacer(),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          children: [
            pw.Column(
              children: [
             pw.Container(width: 200, height: 1, color: PdfColors.black),
             pw.SizedBox(height: 5),
             pw.Text('CoCal AI Coach', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.grey600)),
              ],
            )
          ],
        ),
         ],
       ),
        ),
      ],
    );
     },
   ),
    );

    pdf.addPage(
   pw.MultiPage(
     pageFormat: PdfPageFormat.a4,
     build: (pw.Context context) {
    return [
      pw.Text('Yearly Breakdown', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 20),
      pw.TableHelper.fromTextArray(
        headers: ['Month', 'Score', 'Cals (Avg)', 'Exercise', 'Weight Change', 'Verdict'],
        data: monthlyStats.values.map((m) {
       final monthName = DateFormat('MMM').format(DateTime(year, m.month));
       final weightTrend = m.weightChange > 0 ? '+${m.weightChange.toStringAsFixed(1)}' : m.weightChange.toStringAsFixed(1);
       return [
         monthName,
         m.hasData ? m.score.toStringAsFixed(1) : '-',
         m.hasData ? m.avgCalories.round() : '-',
         '${m.totalExerciseMin} min',
         '$weightTrend kg',
         m.verdict
       ];
        }).toList(),
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
        headerDecoration: const pw.BoxDecoration(color: PdfColors.teal),
      ),
    ];
     },
   ),
    );

    return pdf.save();
  }

  String _getBadge(double score) {
    if (score >= 8.5) return 'GOLD';
    if (score >= 7.0) return 'SILVER';
    if (score >= 5.0) return 'BRONZE';
    return 'PARTICIPANT';
  }

  pw.Widget _buildCertStat(String label, String value) {
    return pw.Column(
      children: [
     pw.Text(value, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800)),
     pw.Text(label, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
      ],
    );
  }
}

class _MonthStat {
  final int month;
  int logsCount = 0;
  int logsInTarget = 0;
  double totalCalories = 0;
  double startWeight = 0;
  double endWeight = 0;
  int totalExerciseMin = 0;
  
  double score = 0;
  bool hasData = false;

  _MonthStat({required this.month});

  void addSummary(DailySummary s, Profile? p) {
    hasData = true;
    logsCount++;
    totalCalories += s.totalCalories;
    final target = p?.dailyCalorieTarget ?? 2000;
    final diff = (s.totalCalories - target).abs();
    if (diff / target <= 0.1) {
   logsInTarget++;
    }
  }

  void addWeight(WeightLog w) {
    if (startWeight == 0 || w.loggedAt.day < 15) startWeight = w.weightKg;
    endWeight = w.weightKg;
  }

  void addExercise(ExerciseLog e) {
    totalExerciseMin += e.durationMinutes;
  }

  void calculateScore() {
    if (!hasData) return;
    final consistencyScore = (logsCount / 20).clamp(0.0, 1.0) * 10;
    final adherenceScore = logsCount > 0 ? (logsInTarget / logsCount) * 10 : 0.0;
    final exerciseScore = (totalExerciseMin / 600).clamp(0.0, 1.0) * 10;
    score = (consistencyScore * 0.3) + (adherenceScore * 0.4) + (exerciseScore * 0.3);
  }

  double get avgCalories => logsCount > 0 ? totalCalories / logsCount : 0;
  double get weightChange => endWeight > 0 && startWeight > 0 ? endWeight - startWeight : 0;
  
  String get verdict {
     if (!hasData) return 'No Data';
     if (score >= 8) return 'Excellent';
     if (score >= 6) return 'Good';
     if (score >= 4) return 'Average';
     return 'Needs Work';
  }
}
